### ISSUE TITLE
BUG: Using os.getenv ("HOME") does not properly retrieve the user directory on Windows

### ISSUE THREAD

**Issue by immortal521** [Kurama622/llm.nvim#11]
can use 
`os.getenv ("USERPROFILE")`

**Comment by immortal521** [comment]
This issue is raised because in the Windows environment, an error will be reported when opening the chat interface
``` 
0:07:19 msg_showcmd ^[
   Error  0:07:21 msg_show.lua_error Error executing Lua callback: ...a/Local/nvim-data/lazy/llm.nvim/lua/llm/common/input.lua:4: loop or previous error loading module 'llm.config'
stack traceback:
	[C]: in function 'require'
	...a/Local/nvim-data/lazy/llm.nvim/lua/llm/common/input.lua:4: in main chunk
	[C]: in function 'require'
	...ppData/Local/nvim-data/lazy/llm.nvim/lua/llm/session.lua:3: in main chunk
	[C]: in function 'require'
	...tal/AppData/Local/nvim-data/lazy/llm.nvim/plugin/llm.lua:2: in function <...tal/AppData/Local/nvim-data/lazy/llm.nvim/plugin/llm.lua:1>
   Error  0:07:21 notify.error lazy.nvim Failed to run `config` for llm.nvim

...AppData/Local/nvim-data/lazy/llm.nvim/lua/llm/config.lua:150: attempt to concatenate local 'HOME' (a nil value)

# stacktrace:
  - llm.nvim\lua\llm\config.lua:150
  - llm.nvim\lua\llm\common\tools.lua:7
  - ~/AppData/Local/nvim/lua/plugins/llm.nvim.lua:6 _in_ **config**
 ```

**Comment by Kurama622** [comment]
ok，I'll add system judgment，thx!



---- Replied Message ----
| From | ***@***.***> |
| Date | 12/11/2024 00:09 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [Kurama622/llm.nvim] BUG: Using os.getenv ("HOME") does not properly retrieve the user directory on Windows (Issue #11) |

This issue is raised because in the Windows environment, an error will be reported when opening the chat interface

0:07:19 msg_showcmd ^[
   Error  0:07:21 msg_show.lua_error Error executing Lua callback: ...a/Local/nvim-data/lazy/llm.nvim/lua/llm/common/input.lua:4: loop or previous error loading module 'llm.config'
stack traceback:
	[C]: in function 'require'
	...a/Local/nvim-data/lazy/llm.nvim/lua/llm/common/input.lua:4: in main chunk
	[C]: in function 'require'
	...ppData/Local/nvim-data/lazy/llm.nvim/lua/llm/session.lua:3: in main chunk
	[C]: in function 'require'
	...tal/AppData/Local/nvim-data/lazy/llm.nvim/plugin/llm.lua:2: in function <...tal/AppData/Local/nvim-data/lazy/llm.nvim/plugin/llm.lua:1>
   Error  0:07:21 notify.error lazy.nvim Failed to run `config` for llm.nvim

...AppData/Local/nvim-data/lazy/llm.nvim/lua/llm/config.lua:150: attempt to concatenate local 'HOME' (a nil value)

# stacktrace:
  - llm.nvim\lua\llm\config.lua:150
  - llm.nvim\lua\llm\common\tools.lua:7
  - ~/AppData/Local/nvim/lua/plugins/llm.nvim.lua:6 _in_ **config**

**Comment by Kurama622** [comment]
Updated, try switching to the Windows branch.
